/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author NUPSI-04
 */
public class FuncionarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pessoa
     */
    public FuncionarioView() {
        initComponents();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(19, 14, 27, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(19, 34, 405, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(19, 80, 405, 20);

        jLabel2.setText("Endereço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 60, 45, 14);

        jLabel3.setText("Cidade/Estado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(19, 106, 70, 14);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(19, 126, 405, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(19, 172, 405, 20);

        jLabel4.setText("Tel Residêncial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(19, 152, 70, 14);

        jLabel5.setText("Tel Comercial (1)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(19, 198, 80, 14);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(19, 218, 405, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(19, 264, 405, 20);

        jLabel6.setText("Tel Comercial (2)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(19, 244, 80, 14);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(19, 310, 405, 20);

        jLabel7.setText("Celular (1)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(19, 290, 50, 14);

        jLabel8.setText("Celular (2)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(19, 336, 50, 14);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(19, 356, 405, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(19, 402, 405, 20);

        jLabel9.setText("Celular (3)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(19, 382, 50, 14);

        jLabel10.setText("Email");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(19, 428, 24, 14);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(19, 448, 405, 20);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(19, 494, 405, 20);

        jLabel11.setText("Setor");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(19, 474, 26, 14);

        jLabel12.setText("Ramal");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(19, 520, 29, 14);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(19, 540, 405, 20);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(19, 586, 405, 20);

        jLabel13.setText("Dia");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(19, 566, 15, 14);

        jLabel14.setText("Observação");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(19, 658, 58, 14);

        jLabel15.setText("Filtro");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(456, 14, 24, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Endereço", "Cidade/Estado", "Departamento", " " }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(95, 23));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(484, 14, 265, 23);

        jButton1.setText("Buscar");
        getContentPane().add(jButton1);
        jButton1.setBounds(1028, 14, 82, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Leonardo Barcelos", "Rua das Flores 278", "Frutal/MG", "34 3423-4523", "34 3423-9874", "34 3423-5429", "17 99652-3217", "34 8125-3645", "11 98452-3674", "leonardo@uemg.br", "Informática", "2563", "Segunda/Quarta/Sexta", "19:00 as 22:40", "Sem observação"},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Cidade/Estado", "Tel Residêncial", "Tel Comercial (1)", "Tel Comercial (2)", "Celular (1)", "Celular (2)", "Celular (3)", "Email", "Departamento", "Ramal", "Dia", "Horário", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(456, 43, 1061, 657);

        jCheckBox1.setText("Docente");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(20, 730, 80, 23);

        jButton2.setText("Novo");
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 710, 77, 23);

        jButton3.setText("Salvar");
        getContentPane().add(jButton3);
        jButton3.setBounds(540, 710, 74, 23);

        jButton4.setText("Excluir");
        getContentPane().add(jButton4);
        jButton4.setBounds(620, 710, 76, 23);

        jButton5.setText("Alterar");
        getContentPane().add(jButton5);
        jButton5.setBounds(700, 710, 85, 23);

        jButton6.setText(">>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1031, 718, 49, 23);

        jButton7.setText("<<");
        getContentPane().add(jButton7);
        jButton7.setBounds(946, 718, 49, 23);

        jLabel16.setText("0/0");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1005, 722, 16, 14);

        jLabel17.setText("Ir para:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1270, 720, 37, 20);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(1310, 720, 53, 30);

        jTextField16.setPreferredSize(new java.awt.Dimension(6, 23));
        getContentPane().add(jTextField16);
        jTextField16.setBounds(759, 14, 263, 23);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(19, 632, 405, 20);

        jLabel18.setText("Horário");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(19, 612, 35, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(19, 678, 405, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
