/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UsuarioDAO;
import java.awt.Event;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import model.UsuarioM;

/**
 *
 * @author Leopo
 */
public class InicialView extends javax.swing.JFrame {

    /**
     * Creates new form InicialView
     */
    public InicialView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        
        
        URL url = this.getClass().getResource("/view/icones/icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConvidado = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agenda");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        btnConvidado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnConvidado.setText("Convidado");
        btnConvidado.setPreferredSize(new java.awt.Dimension(136, 29));
        btnConvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvidadoActionPerformed(evt);
            }
        });
        btnConvidado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConvidadoKeyPressed(evt);
            }
        });

        btnAdministrador.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdministrador.setText("Administrador");
        btnAdministrador.setPreferredSize(new java.awt.Dimension(136, 29));
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        btnAdministrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdministradorKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione o tipo do usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConvidado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvidado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        LoginView login = new LoginView();
        this.dispose();
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvidadoActionPerformed
        UsuarioM usuarioM = new UsuarioM();
        usuarioM = null;
        String convidado = "convidado";
        try{
        usuarioM = UsuarioDAO.valida(convidado,convidado);
        this.dispose();
        }
        catch(Exception ex){
         ex.printStackTrace();
        }
        PrincipalView principal = new PrincipalView(usuarioM);

    }//GEN-LAST:event_btnConvidadoActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void btnAdministradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdministradorKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        LoginView LoginView = new LoginView();
        }
    }//GEN-LAST:event_btnAdministradorKeyPressed

    private void btnConvidadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConvidadoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        UsuarioM usuarioM = null;
        String convidado = "convidado";
        try{
        usuarioM = UsuarioDAO.valida(convidado,convidado);
        this.dispose();
        }
        catch(Exception ex){
         ex.printStackTrace();
        }
        PrincipalView principal = new PrincipalView(usuarioM);
        }
    }//GEN-LAST:event_btnConvidadoKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnConvidado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
